---
Name: TrackingModule
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Tracking\Extensions\TrackingSiteConfigExtension
Page:
  extensions:
    - Tracking\Extensions\TrackingPageExtension